blueprint:
  name: Smart Motion Lights & Switches
  description: >
    Version: 1.6 Set kelvin within capabilities
    
    Turn on lights when motion is detected IF:
    1. It is Night (based on Sun Schedule)
    OR
    2. It is Dark (based on Lux Sensor, if provided)
  domain: automation
  # Ensure this matches your GitHub URL exactly
  source_url: https://github.com/rgafonso/homeassistant/blob/main/smart-lights.yaml
  input:
    # ----------------------------------------------------------------
    # SECTION 1: MOTION & LIGHT
    # ----------------------------------------------------------------
    section_core:
      name: Motion & Light
      description: The main settings for your automation.
      icon: mdi:run
      input:
        motion_entity:
          name: Motion Sensor
          description: The starting trigger
          selector:
            entity:
              domain: binary_sensor
              device_class: motion
        target_light:
          name: Lights & Switches
          description: Select all that you wish to enable
          selector:
            target:
              entity:
                domain: 
                  - light
                  - switch
        no_motion_wait:
          name: Wait Time (Seconds)
          description: The time which after no motion detected, everything resets
          default: 30
          selector:
            number:
              min: 0
              max: 300
              unit_of_measurement: seconds

    # ----------------------------------------------------------------
    # SECTION 2: SUN SCHEDULE (Primary)
    # ----------------------------------------------------------------
    section_sun:
      name: Sun Schedule
      description: The primary rule. Defines "Night Time".
      icon: mdi:weather-sunset
      input:
        sunset_offset:
          name: Sunset Offset
          description: >
            Positive (e.g. 00:30:00) starts after sunset.
            Negative (e.g. -00:15:00) starts before sunset.
          default: "00:30:00"
          selector:
            text: {}
        sunrise_offset:
          name: Sunrise Offset
          description: >
            Negative (e.g. -00:30:00) stops after sunrise.
            Positive (e.g. 00:15:00) stops before sunrise.
          default: "-00:30:00"
          selector:
            text: {}

    # ----------------------------------------------------------------
    # SECTION 3: LUX OVERRIDE (Optional)
    # ----------------------------------------------------------------
    section_lux:
      name: Lux (Optional)
      description: Triggers even during the day if it's dark (Cloudy/Indoors).
      icon: mdi:brightness-6
      collapsed: true
      input:
        lux_sensor:
          name: Illuminance Sensor
          description: If set, lights turn on when below threshold (regardless of sun).
          default: []
          selector:
            entity:
              domain: sensor
              device_class: illuminance
              multiple: false
        lux_threshold:
          name: Lux Threshold
          description: Always trigger if lux is below this value and illuminance sensor set.
          default: 50
          selector:
            number:
              min: 0
              max: 1000

    # ----------------------------------------------------------------
    # SECTION 4: LIGHT PROPERTIES (Optional)
    # ----------------------------------------------------------------
    section_light_settings:
      name: Advanced Light Settings (Optional)
      description: Optionally choose brightness & color temperature (if supported).
      icon: mdi:lightbulb-on-50
      collapsed: true
      input:
        target_brightness:
          name: Brightness %
          default: 0
          selector:
            number:
              min: 0
              max: 100
              unit_of_measurement: "%"
        target_kelvin:
          name: Color Temp (K)
          default: 0
          selector:
            number:
              min: 0
              max: 6500
              unit_of_measurement: K

mode: restart
max_exceeded: silent

variables:
  var_lux_sensor: !input lux_sensor
  var_target_brightness: !input target_brightness
  var_target_kelvin: !input target_kelvin
  var_target_light: !input target_light
  safe_kelvin: >
    {# 1. Initialize with User Input #}
    {% set ns = namespace(kelvin=var_target_kelvin | int, lights=[]) %}
    
    {# 2. Get direct Entities #}
    {% set entities = var_target_light.entity_id | default([]) %}
    {% set ns.lights = ns.lights + entities %}

    {# 3. Get entities from Areas (Fix: Loop through the list) #}
    {% set area_ids = var_target_light.area_id | default([]) %}
    {% for area in area_ids %}
      {% set ns.lights = ns.lights + area_entities(area) %}
    {% endfor %}

    {# 4. Get entities from Devices (Fix: Loop through devices too) #}
    {% set device_ids = var_target_light.device_id | default([]) %}
    {% for dev in device_ids %}
      {% set ns.lights = ns.lights + device_entities(dev) %}
    {% endfor %}

    {# 5. Clean up duplicates #}
    {% set all_lights = ns.lights | unique | list %}
   
    {# 6. Run the Safety Loop #}
    {% if ns.kelvin > 0 %}
      {% for light in all_lights %}
        {# SAFETY: Default to 0/10000 for non-color devices (switches/dimmers) #}
        {% set current_min = state_attr(light, 'min_color_temp_kelvin') | default(0, true) %}
        {% set current_max = state_attr(light, 'max_color_temp_kelvin') | default(10000, true) %}
        
        {# The Clamp Logic #}
        {% set ns.kelvin = [[ns.kelvin, current_min]|max, current_max]|min %}
      {% endfor %}
    {% endif %}
   
    {# 7. Output Result #}
    {{ ns.kelvin }}

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: "on"

condition:
  - condition: or
    conditions:
      # RULE 1: Sun Schedule
      - condition: sun
        after: sunset
        after_offset: !input sunset_offset
        before: sunrise
        before_offset: !input sunrise_offset

      # RULE 2: Lux Override (Only if sensor is set)
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ var_lux_sensor != [] }}"
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: !input lux_threshold

action:
  - choose:
      # SCENARIO 1: User set both Brightness and temperature
      - conditions:
          - condition: template
            value_template: "{{ var_target_brightness | int > 0 }}"
          - condition: template
            value_template: "{{ var_target_kelvin | int > 0 }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: "{{ var_target_brightness }}"
              kelvin: "{{ safe_kelvin }}"
            # FIX: Prevent crash if device rejects the color
            continue_on_error: true

      # SCENARIO 2: User set only Brightness
      - conditions:
          - condition: template
            value_template: "{{ var_target_brightness | int > 0 }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: "{{ var_target_brightness }}"
            continue_on_error: true

      # SCENARIO 3: User set only temperature
      - conditions:
          - condition: template
            value_template: "{{ var_target_kelvin | int > 0 }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              kelvin: "{{ safe_kelvin }}"
            continue_on_error: true
          
    # SCENARIO 4 (Default): User set NOTHING -> Just Turn On (Use Memory)
    default:
      - service: homeassistant.turn_on
        target: !input target_light

  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        to: "off"
        for:
          seconds: !input no_motion_wait

  - service: homeassistant.turn_off
    target: !input target_light
