blueprint:
  name: Smart Motion Light (Sun + Lux)
  description: >
    Turn on a light on motion if it is Night (Sun-based) OR if it is dark (Lux-based).
    Turns off after a set time of no motion.
  domain: automation
  # Ensure this matches your GitHub URL exactly
  source_url: https://github.com/rgafonso/homeassistant/blob/main/smart-lights.yaml
  input:
    # ----------------------------------------------------------------
    # SECTION 1: CORE SETTINGS (Always Visible)
    # ----------------------------------------------------------------
    section_core:
      name: Motion & Light
      description: The main settings for your automation.
      icon: mdi:run
      input:
        motion_entity:
          name: Motion Sensor
          selector:
            entity:
              domain: binary_sensor
              device_class: motion
        target_light:
          name: Light or Switch
          selector:
            target:
              entity:
                domain: 
                  - light
                  - switch
        no_motion_wait:
          name: Wait Time (Seconds)
          description: Time to wait after motion stops before turning off.
          default: 120
          selector:
            number:
              min: 0
              max: 3600
              unit_of_measurement: seconds

    # ----------------------------------------------------------------
    # SECTION 2: SUN CONSTRAINTS (Always Visible)
    # ----------------------------------------------------------------
    section_sun:
      name: Sun Schedule
      description: Define the "Night" window relative to the sun.
      icon: mdi:weather-sunset
      input:
        sunset_offset:
          name: Sunset Offset
          description: Negative for before sunset, positive for after (e.g., -00:30:00).
          default: "-00:30:00"
          selector:
            text: {}
        sunrise_offset:
          name: Sunrise Offset
          description: Negative for before sunrise, positive for after (e.g., 00:30:00).
          default: "00:30:00"
          selector:
            text: {}

    # ----------------------------------------------------------------
    # SECTION 3: ADVANCED LIGHTING (Collapsed by Default)
    # ----------------------------------------------------------------
    section_light_settings:
      name: Advanced Light Settings (Optional)
      description: Force specific brightness or color when turning on.
      icon: mdi:lightbulb-cog
      collapsed: true
      input:
        target_brightness:
          name: Brightness %
          description: Leave at 0 to use the light's current setting (Disabled).
          default: 0
          selector:
            number:
              min: 0
              max: 100
              unit_of_measurement: "%"
        target_kelvin:
          name: Color Temp (K)
          description: Leave at 0 to use the light's current setting (Disabled).
          default: 0
          selector:
            number:
              min: 0
              max: 6500
              unit_of_measurement: K

    # ----------------------------------------------------------------
    # SECTION 4: LUX OVERRIDE (Collapsed by Default)
    # ----------------------------------------------------------------
    section_lux:
      name: Lux Sensor Override (Optional)
      description: Enable this to turn on lights during the day if it is dark.
      icon: mdi:brightness-6
      collapsed: true
      input:
        lux_sensor:
          name: Illuminance Sensor
          description: Select a sensor to enable this feature.
          default: []
          selector:
            entity:
              domain: sensor
              device_class: illuminance
              multiple: false
        lux_threshold:
          name: Lux Threshold
          description: Trigger if lux is below this value.
          default: 50
          selector:
            number:
              min: 0
              max: 1000

mode: restart
max_exceeded: silent

variables:
  var_lux_sensor: !input lux_sensor
  var_target_brightness: !input target_brightness
  var_target_kelvin: !input target_kelvin
  var_target_light: !input target_light

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: "on"

condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: !input sunset_offset
        before: sunrise
        before_offset: !input sunrise_offset
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ var_lux_sensor != [] }}"
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: !input lux_threshold

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ var_target_brightness | int > 0 }}"
              - condition: template
                value_template: "{{ var_target_kelvin | int > 0 }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: >
                {% if var_target_brightness | int > 0 %}
                  {{ var_target_brightness }}
                {% else %}
                  {{ state_attr(var_target_light, 'brightness') | default(255) | int / 2.55 }}
                {% endif %}
              kelvin: >
                {% if var_target_kelvin | int > 0 %}
                  {{ var_target_kelvin }}
                {% else %}
                  {{ state_attr(var_target_light, 'color_temp_kelvin') | default(3000) }}
                {% endif %}
    default:
      - service: homeassistant.turn_on
        target: !input target_light

  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        to: "off"
        for:
          seconds: !input no_motion_wait

  - service: homeassistant.turn_off
    target: !input target_light
