blueprint:
  name: Smart Motion Light (Universal)
  description: >
    Version: 3.0 (Exclusive Modes)
    
    A universal blueprint for two distinct use cases:
    1. OUTDOOR: Uses Sun Schedule (Sunset/Sunrise).
    2. INDOOR: Uses Lux Sensor (ignores Sun).
    
    Can also combine them if desired, but designed for exclusive use.
  domain: automation
  # Ensure this matches your GitHub URL exactly
  source_url: https://github.com/rgafonso/homeassistant/blob/main/smart-lights.yaml
  input:
    # ----------------------------------------------------------------
    # SECTION 1: MOTION & LIGHT (Common)
    # ----------------------------------------------------------------
    section_core:
      name: Motion & Light
      description: The main settings for your automation.
      icon: mdi:run
      input:
        motion_entity:
          name: Motion Sensor
          selector:
            entity:
              domain: binary_sensor
              device_class: motion
        target_light:
          name: Light or Switch
          selector:
            target:
              entity:
                domain: 
                  - light
                  - switch
        no_motion_wait:
          name: Wait Time (Seconds)
          default: 30
          selector:
            number:
              min: 0
              max: 3600
              unit_of_measurement: seconds

    # ----------------------------------------------------------------
    # SECTION 2: OUTDOOR MODE (Sun Schedule)
    # ----------------------------------------------------------------
    section_sun:
      name: Outdoor / Sun Settings
      description: Configure this for Outdoor lights.
      icon: mdi:weather-sunset
      input:
        use_sun:
          name: Use Sun Schedule?
          description: >
            Disable this for Indoor (Lux-only) automations. 
            If OFF, sunset/sunrise is ignored.
          default: true
          selector:
            boolean: {}
        sunset_offset:
          name: Sunset Offset
          description: Positive to start AFTER sunset (e.g. 00:15:00).
          default: "00:15:00"
          selector:
            text: {}
        sunrise_offset:
          name: Sunrise Offset
          description: Negative to stop BEFORE sunrise (e.g. -00:15:00).
          default: "-00:15:00"
          selector:
            text: {}

    # ----------------------------------------------------------------
    # SECTION 3: INDOOR MODE (Lux Sensor)
    # ----------------------------------------------------------------
    section_lux:
      name: Indoor / Lux Settings
      description: Configure this for Indoor lights (requires sensor).
      icon: mdi:brightness-6
      # Collapsed by default to keep UI clean if using Outdoor mode
      collapsed: true
      input:
        lux_sensor:
          name: Illuminance Sensor
          description: Required if "Use Sun Schedule" is OFF.
          default: []
          selector:
            entity:
              domain: sensor
              device_class: illuminance
              multiple: false
        lux_threshold:
          name: Lux Threshold
          description: Trigger if lux is below this value.
          default: 50
          selector:
            number:
              min: 0
              max: 1000

    # ----------------------------------------------------------------
    # SECTION 4: LIGHT PROPERTIES (Optional)
    # ----------------------------------------------------------------
    section_light_settings:
      name: Advanced Light Settings (Optional)
      icon: mdi:lightbulb-settings
      collapsed: true
      input:
        target_brightness:
          name: Brightness %
          default: 0
          selector:
            number:
              min: 0
              max: 100
              unit_of_measurement: "%"
        target_kelvin:
          name: Color Temp (K)
          default: 0
          selector:
            number:
              min: 0
              max: 6500
              unit_of_measurement: K

mode: restart
max_exceeded: silent

variables:
  var_lux_sensor: !input lux_sensor
  var_use_sun: !input use_sun
  var_target_brightness: !input target_brightness
  var_target_kelvin: !input target_kelvin
  var_target_light: !input target_light

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: "on"

condition:
  - condition: or
    conditions:
      # ----------------------------------------------------
      # LOGIC A: Sun Schedule (Only runs if use_sun is TRUE)
      # ----------------------------------------------------
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ var_use_sun }}"
          - condition: sun
            after: sunset
            after_offset: !input sunset_offset
            before: sunrise
            before_offset: !input sunrise_offset

      # ----------------------------------------------------
      # LOGIC B: Lux Sensor (Only runs if Sensor is set)
      # ----------------------------------------------------
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ var_lux_sensor != [] }}"
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: !input lux_threshold

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ var_target_brightness | int > 0 }}"
              - condition: template
                value_template: "{{ var_target_kelvin | int > 0 }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: >
                {% if var_target_brightness | int > 0 %}
                  {{ var_target_brightness }}
                {% else %}
                  {{ state_attr(var_target_light, 'brightness') | default(255) | int / 2.55 }}
                {% endif %}
              kelvin: >
                {% if var_target_kelvin | int > 0 %}
                  {{ var_target_kelvin }}
                {% else %}
                  {{ state_attr(var_target_light, 'color_temp_kelvin') | default(3000) }}
                {% endif %}
    default:
      - service: homeassistant.turn_on
        target: !input target_light

  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        to: "off"
        for:
          seconds: !input no_motion_wait

  - service: homeassistant.turn_off
    target: !input target_light
