blueprint:
  name: Smart Motion Lights & Switches
  description: |
    Version: 1.0.3
    
    Turn on lights when motion, occupancy or presence is detected if it's night time, based on sunset/sunrise (with offsets) for your location.
    Can be overriden by lux (illuminance) sensor and threshold, useful for indoors or cloudy days
  domain: automation
  source_url: https://github.com/rgafonso/homeassistant/blob/main/smart-lights.yaml
  input:
    section_core:
      name: Sensor + Lights & Switches
      description: The main settings for your automation.
      icon: mdi:run
      input:
        main_sensor:
          name: Main Sensor
          description: Choose a motion, occupancy or presence sensor
          selector:
            entity:
              domain: binary_sensor
              device_class:
                - motion
                - occupancy
                - presence
        target_entities:
          name: Lights & Switches
          description: Select all that you wish to enable
          selector:
            target:
              entity:
                domain: 
                  - light
                  - switch
        off_timer:
          name: Wait Time (Seconds)
          description: The time which after sensor is off, the lights & switches also turn off
          default: 30
          selector:
            number:
              min: 0
              max: 300
              unit_of_measurement: seconds
    section_sun:
      name: Sun Schedule
      description: Mainly designed for night time. Can be overridden by lux (illuminance)
      icon: mdi:weather-sunset
      input:
        sunset_offset:
          name: Sunset Offset
          description: >
            Positive (e.g. 00:30:00) starts after sunset.
            Negative (e.g. -00:15:00) starts before sunset.
          default: "00:30:00"
          selector:
            text: {}
        sunrise_offset:
          name: Sunrise Offset
          description: >
            Negative (e.g. -00:30:00) stops after sunrise.
            Positive (e.g. 00:15:00) stops before sunrise.
          default: "-00:30:00"
          selector:
            text: {}
    section_illuminance:
      name: Lux Settings (Overrides Sun Schedule)
      description: Triggers lights based on illuminance, useful for cloudy indoors.
      icon: mdi:brightness-6
      collapsed: true
      input:
        illuminance_sensor:
          name: Lux (illuminance) Sensor
          description: If set, lights turn on when below threshold (regardless of sun).
          default: []
          selector:
            entity:
              domain: sensor
              device_class: illuminance
              multiple: false
        illuminance_threshold:
          name: Lux (illuminance) Threshold
          description: Always trigger if lux is below this value and lux sensor set.
          default: 50
          selector:
            number:
              min: 0
              max: 1000

mode: restart
max_exceeded: silent

variables:
  illuminance_sensor: !input illuminance_sensor
  # We need to map the motion sensor to a variable for the template check
  main_sensor: !input main_sensor

trigger:
  - platform: state
    entity_id: !input main_sensor
    to: "on"
    alias: "Motion Detected"

condition:
  - condition: or
    conditions:
      # RULE 1: Sun Schedule
      - condition: sun
        after: sunset
        after_offset: !input sunset_offset
        before: sunrise
        before_offset: !input sunrise_offset

      # RULE 2: Lux Override (Only if sensor is set)
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ illuminance_sensor != [] }}"
          - condition: numeric_state
            entity_id: !input illuminance_sensor
            below: !input illuminance_threshold

action:
  - service: homeassistant.turn_on
    target: !input target_entities

  - if:
      - condition: state
        entity_id: !input main_sensor
        state: "on"
    then:
      - wait_for_trigger:
          - platform: state
            entity_id: !input main_sensor
            to: "off"

  - delay: 
      seconds: !input off_timer

  - service: homeassistant.turn_off
    target: !input target_entities
